### ISSUE TITLE
Larger output example

### ISSUE THREAD

**Issue by dillingham** [jenstornell/tailwind-gradient-designer#8]
![example](https://user-images.githubusercontent.com/29180903/91645156-c1cc7600-ea10-11ea-911d-df2f00fe0456.png)

it's helpful if the example is a bit larger.. 300px is nice.. personally

**Comment by jenstornell** [comment]
Yes, I agree. I'm working on a new version and it will include a bigger preview. Overall, it will use the screen much better.

I don't know when it's going to be released, but I'm working on it from time to time.

**Comment by dillingham** [comment]
@jenstornell awesome! Its easy enough to inspect element for now. Thanks for the tool
